"""initial schema

Revision ID: 5fd2ed5269af
Revises: 
Create Date: 2026-05-09 14:18:52.082635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5fd2ed5269af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('week_start_day', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('suspend_reason', sa.String(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_table('parent_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('revoke_reason', sa.String(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['restored_by_parent_id'], ['parent_users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_parent_id'], ['parent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_users_email'), 'parent_users', ['email'], unique=True)
    op.create_index(op.f('ix_parent_users_google_sub'), 'parent_users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_parent_users_id'), 'parent_users', ['id'], unique=False)
    op.create_foreign_key('fk_families_restored_by_parent_id_parent_users', 'families', 'parent_users', ['restored_by_parent_id'], ['id'])
    op.create_foreign_key('fk_families_suspended_by_parent_id_parent_users', 'families', 'parent_users', ['suspended_by_parent_id'], ['id'])
    op.create_table('approved_parent_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('normalized_email', sa.String(), nullable=True),
    sa.Column('approved_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('revoke_reason', sa.String(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_parent_id'], ['parent_users.id'], ),
    sa.ForeignKeyConstraint(['restored_by_parent_id'], ['parent_users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_parent_id'], ['parent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approved_parent_emails_email'), 'approved_parent_emails', ['email'], unique=False)
    op.create_index(op.f('ix_approved_parent_emails_id'), 'approved_parent_emails', ['id'], unique=False)
    op.create_index(op.f('ix_approved_parent_emails_normalized_email'), 'approved_parent_emails', ['normalized_email'], unique=True)
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=False)
    op.create_table('family_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=True),
    sa.Column('invited_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_parent_id'], ['parent_users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['invited_by_parent_id'], ['parent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_invites_email'), 'family_invites', ['email'], unique=False)
    op.create_index(op.f('ix_family_invites_id'), 'family_invites', ['id'], unique=False)
    op.create_index(op.f('ix_family_invites_token_hash'), 'family_invites', ['token_hash'], unique=True)
    op.create_table('preset_behaviours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preset_behaviours_id'), 'preset_behaviours', ['id'], unique=False)
    op.create_table('registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('normalized_email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_parent_id'], ['parent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_requests_email'), 'registration_requests', ['email'], unique=False)
    op.create_index(op.f('ix_registration_requests_id'), 'registration_requests', ['id'], unique=False)
    op.create_index(op.f('ix_registration_requests_normalized_email'), 'registration_requests', ['normalized_email'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_id'), 'rewards', ['id'], unique=False)
    op.create_table('calendar_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('created_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=True),
    sa.Column('is_rewardable', sa.Boolean(), nullable=True),
    sa.Column('points_value', sa.Integer(), nullable=True),
    sa.Column('recurrence_type', sa.String(), nullable=True),
    sa.Column('recurrence_days', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by_parent_id'], ['parent_users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_entries_id'), 'calendar_entries', ['id'], unique=False)
    op.create_table('child_device_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('created_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by_parent_id'], ['parent_users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_device_invites_id'), 'child_device_invites', ['id'], unique=False)
    op.create_index(op.f('ix_child_device_invites_token_hash'), 'child_device_invites', ['token_hash'], unique=True)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('jar', sa.Enum('spending', 'savings', name='jartype', native_enum=False), nullable=True),
    sa.Column('transaction_type', sa.Enum('award', 'penalty', 'savings_deposit', 'savings_withdrawal', 'redemption_hold', 'redemption_approved', 'redemption_rejected', 'adjustment', 'calendar_task', name='transactiontype', native_enum=False), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by_parent_id'], ['parent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_transactions_id'), 'ledger_transactions', ['id'], unique=False)
    op.create_table('pet_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('lifetime_points', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.Enum('egg', 'hatchling', 'cub', 'hero', 'beast', name='petstage', native_enum=False), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id')
    )
    op.create_index(op.f('ix_pet_progress_id'), 'pet_progress', ['id'], unique=False)
    op.create_table('redemption_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='redemptionstatus', native_enum=False), nullable=True),
    sa.Column('parent_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_parent_id'], ['parent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemption_requests_id'), 'redemption_requests', ['id'], unique=False)
    op.create_table('school_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('needed_item', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by_parent_id'], ['parent_users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_items_id'), 'school_items', ['id'], unique=False)
    op.create_table('weekly_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('week_end_date', sa.Date(), nullable=True),
    sa.Column('bonus_date', sa.Date(), nullable=True),
    sa.Column('required_task_count', sa.Integer(), nullable=True),
    sa.Column('completed_task_count', sa.Integer(), nullable=True),
    sa.Column('streak_earned', sa.Boolean(), nullable=True),
    sa.Column('bonus_multiplier', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'week_start_date', name='_child_week_streak_uc')
    )
    op.create_index(op.f('ix_weekly_streaks_id'), 'weekly_streaks', ['id'], unique=False)
    op.create_table('calendar_task_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('occurrence_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('base_points', sa.Integer(), nullable=True),
    sa.Column('bonus_multiplier_applied', sa.Float(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('streak_source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['calendar_entries.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_parent_id'], ['parent_users.id'], ),
    sa.ForeignKeyConstraint(['streak_source_id'], ['weekly_streaks.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'child_id', 'occurrence_date', name='_task_occurrence_uc')
    )
    op.create_index(op.f('ix_calendar_task_completions_id'), 'calendar_task_completions', ['id'], unique=False)
    op.create_table('child_device_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('invite_id', sa.Integer(), nullable=True),
    sa.Column('session_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['invite_id'], ['child_device_invites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_device_sessions_id'), 'child_device_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_child_device_sessions_session_hash'), 'child_device_sessions', ['session_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_families_suspended_by_parent_id_parent_users', 'families', type_='foreignkey')
    op.drop_constraint('fk_families_restored_by_parent_id_parent_users', 'families', type_='foreignkey')
    op.drop_index(op.f('ix_child_device_sessions_session_hash'), table_name='child_device_sessions')
    op.drop_index(op.f('ix_child_device_sessions_id'), table_name='child_device_sessions')
    op.drop_table('child_device_sessions')
    op.drop_index(op.f('ix_calendar_task_completions_id'), table_name='calendar_task_completions')
    op.drop_table('calendar_task_completions')
    op.drop_index(op.f('ix_weekly_streaks_id'), table_name='weekly_streaks')
    op.drop_table('weekly_streaks')
    op.drop_index(op.f('ix_school_items_id'), table_name='school_items')
    op.drop_table('school_items')
    op.drop_index(op.f('ix_redemption_requests_id'), table_name='redemption_requests')
    op.drop_table('redemption_requests')
    op.drop_index(op.f('ix_pet_progress_id'), table_name='pet_progress')
    op.drop_table('pet_progress')
    op.drop_index(op.f('ix_ledger_transactions_id'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_child_device_invites_token_hash'), table_name='child_device_invites')
    op.drop_index(op.f('ix_child_device_invites_id'), table_name='child_device_invites')
    op.drop_table('child_device_invites')
    op.drop_index(op.f('ix_calendar_entries_id'), table_name='calendar_entries')
    op.drop_table('calendar_entries')
    op.drop_index(op.f('ix_rewards_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_registration_requests_normalized_email'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_id'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_email'), table_name='registration_requests')
    op.drop_table('registration_requests')
    op.drop_index(op.f('ix_preset_behaviours_id'), table_name='preset_behaviours')
    op.drop_table('preset_behaviours')
    op.drop_index(op.f('ix_family_invites_token_hash'), table_name='family_invites')
    op.drop_index(op.f('ix_family_invites_id'), table_name='family_invites')
    op.drop_index(op.f('ix_family_invites_email'), table_name='family_invites')
    op.drop_table('family_invites')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_approved_parent_emails_normalized_email'), table_name='approved_parent_emails')
    op.drop_index(op.f('ix_approved_parent_emails_id'), table_name='approved_parent_emails')
    op.drop_index(op.f('ix_approved_parent_emails_email'), table_name='approved_parent_emails')
    op.drop_table('approved_parent_emails')
    op.drop_index(op.f('ix_parent_users_id'), table_name='parent_users')
    op.drop_index(op.f('ix_parent_users_google_sub'), table_name='parent_users')
    op.drop_index(op.f('ix_parent_users_email'), table_name='parent_users')
    op.drop_table('parent_users')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
