"""Deterministic PDF/CSV rendering for private school-generated documents."""
from __future__ import annotations

import csv
import html
import io
from pathlib import Path
from typing import Any, Literal

import arabic_reshaper
from bidi.algorithm import get_display
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


Language = Literal["en", "ar"]

FONT_CANDIDATES = (
    (
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
    ),
    (Path("C:/Windows/Fonts/arial.ttf"), Path("C:/Windows/Fonts/arialbd.ttf")),
)

COPY = {
    "en": {
        "behaviour_report": "Behaviour overview report",
        "private": "Private management report - do not publish or use as a public ranking.",
        "period": "Reporting period",
        "scope": "Scope",
        "school": "School",
        "department": "Department",
        "generated": "Generated by Class Hero Hub",
        "filters": "Applied filters",
        "all": "All eligible records",
        "total": "Total events",
        "positive": "Positive",
        "needs_work": "Needs work",
        "ratio": "Positive ratio",
        "students": "Active students",
        "teachers": "Active staff",
        "points": "Signed points",
        "trend": "Daily trend",
        "date": "Date",
        "classes": "Class comparison",
        "grades": "Grade comparison",
        "subjects": "Subject comparison",
        "categories": "Category breakdown",
        "label": "Label",
        "event_register": "Matching event register",
        "time": "Time",
        "student": "Student",
        "staff": "Staff",
        "category": "Category",
        "context": "Context",
        "page": "Page",
        "certificate": "Certificate of recognition",
        "presented_to": "Presented to",
        "award_period": "Award period",
        "certificate_private": "School-confirmed recognition. Shared only with authorised recipients.",
    },
    "ar": {
        "behaviour_report": "تقرير النظرة العامة للسلوك",
        "private": "تقرير إداري خاص - يُحظر نشره أو استخدامه كتصنيف علني.",
        "period": "فترة التقرير",
        "scope": "النطاق",
        "school": "المدرسة",
        "department": "القسم",
        "generated": "أُنشئ بواسطة Class Hero Hub",
        "filters": "عوامل التصفية المطبقة",
        "all": "جميع السجلات المؤهلة",
        "total": "إجمالي الأحداث",
        "positive": "إيجابي",
        "needs_work": "يحتاج إلى تحسين",
        "ratio": "نسبة الإيجابي",
        "students": "الطلاب النشطون",
        "teachers": "الموظفون النشطون",
        "points": "صافي النقاط",
        "trend": "الاتجاه اليومي",
        "date": "التاريخ",
        "classes": "مقارنة الفصول",
        "grades": "مقارنة الصفوف",
        "subjects": "مقارنة المواد",
        "categories": "تفصيل الفئات",
        "label": "البيان",
        "event_register": "سجل الأحداث المطابقة",
        "time": "الوقت",
        "student": "الطالب",
        "staff": "الموظف",
        "category": "الفئة",
        "context": "السياق",
        "page": "الصفحة",
        "certificate": "شهادة تقدير",
        "presented_to": "تُقدّم إلى",
        "award_period": "فترة التكريم",
        "certificate_private": "تقدير مؤكّد من المدرسة، ويُشارك فقط مع المستلمين المصرح لهم.",
    },
}

ACCENTS = {
    "gold": (colors.HexColor("#B7791F"), colors.HexColor("#FFFBEB")),
    "violet": (colors.HexColor("#6D28D9"), colors.HexColor("#F5F3FF")),
    "emerald": (colors.HexColor("#047857"), colors.HexColor("#ECFDF5")),
    "navy": (colors.HexColor("#1E3A8A"), colors.HexColor("#EFF6FF")),
    "burgundy": (colors.HexColor("#9F1239"), colors.HexColor("#FFF1F2")),
}

_fonts_registered = False


def _register_fonts() -> tuple[str, str]:
    global _fonts_registered
    if _fonts_registered:
        return "CHH-Regular", "CHH-Bold"
    for regular, bold in FONT_CANDIDATES:
        if regular.is_file() and bold.is_file():
            pdfmetrics.registerFont(TTFont("CHH-Regular", str(regular)))
            pdfmetrics.registerFont(TTFont("CHH-Bold", str(bold)))
            _fonts_registered = True
            return "CHH-Regular", "CHH-Bold"
    # This fallback keeps English generation available in an unexpected image,
    # while Arabic generation fails clearly instead of rendering black squares.
    return "Helvetica", "Helvetica-Bold"


def _display(value: Any, language: Language) -> str:
    text = str(value if value is not None else "")
    if language == "ar" and any("\u0600" <= char <= "\u06ff" for char in text):
        text = get_display(arabic_reshaper.reshape(text))
    return text


def _csv_safe(value: Any) -> Any:
    """Prevent spreadsheet formula execution for school-entered export values."""
    if value is None or isinstance(value, (bool, int, float)):
        return value
    text = str(value)
    stripped = text.lstrip()
    if stripped and (stripped[0] in "=+-@" or text[0] in "\t\r\n"):
        return f"'{text}"
    return text


def _paragraph(value: Any, style: ParagraphStyle, language: Language) -> Paragraph:
    return Paragraph(html.escape(_display(value, language)), style)


def _styles(language: Language) -> dict[str, ParagraphStyle]:
    regular, bold = _register_fonts()
    if language == "ar" and regular == "Helvetica":
        raise RuntimeError("An Arabic-capable TrueType font is required")
    alignment = TA_RIGHT if language == "ar" else TA_LEFT
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "CHHTitle",
            parent=base["Title"],
            fontName=bold,
            fontSize=22,
            leading=28,
            textColor=colors.HexColor("#111827"),
            alignment=alignment,
        ),
        "heading": ParagraphStyle(
            "CHHHeading",
            parent=base["Heading2"],
            fontName=bold,
            fontSize=13,
            leading=17,
            textColor=colors.HexColor("#312E81"),
            alignment=alignment,
            spaceBefore=5,
            spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "CHHBody",
            parent=base["BodyText"],
            fontName=regular,
            fontSize=8.5,
            leading=12,
            alignment=alignment,
            wordWrap="RTL" if language == "ar" else "LTR",
        ),
        "small": ParagraphStyle(
            "CHHSmall",
            parent=base["BodyText"],
            fontName=regular,
            fontSize=7,
            leading=9,
            textColor=colors.HexColor("#475569"),
            alignment=alignment,
        ),
        "metric": ParagraphStyle(
            "CHHMetric",
            parent=base["BodyText"],
            fontName=bold,
            fontSize=12,
            leading=15,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#111827"),
        ),
        "certificate_title": ParagraphStyle(
            "CHHCertificateTitle",
            parent=base["Title"],
            fontName=bold,
            fontSize=29,
            leading=36,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#111827"),
        ),
        "certificate_name": ParagraphStyle(
            "CHHCertificateName",
            parent=base["Title"],
            fontName=bold,
            fontSize=26,
            leading=34,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#4C1D95"),
        ),
        "centre": ParagraphStyle(
            "CHHCentre",
            parent=base["BodyText"],
            fontName=regular,
            fontSize=11,
            leading=16,
            alignment=TA_CENTER,
        ),
        "centre_bold": ParagraphStyle(
            "CHHCentreBold",
            parent=base["BodyText"],
            fontName=bold,
            fontSize=12,
            leading=17,
            alignment=TA_CENTER,
        ),
    }


def _footer(canvas, doc, *, language: Language, school_name: str) -> None:
    regular, _ = _register_fonts()
    canvas.saveState()
    canvas.setFont(regular, 7)
    canvas.setFillColor(colors.HexColor("#64748B"))
    page = f"{COPY[language]['page']} {doc.page}"
    canvas.drawString(doc.leftMargin, 10 * mm, _display(school_name, language))
    canvas.drawRightString(A4[0] - doc.rightMargin, 10 * mm, _display(page, language))
    canvas.restoreState()


def _summary_table(
    rows: list[dict[str, Any]],
    heading: str,
    language: Language,
    styles,
    *,
    label_heading: str | None = None,
) -> list:
    if not rows:
        return []
    copy = COPY[language]
    head = [label_heading or copy["label"], copy["total"], copy["positive"], copy["needs_work"], copy["points"]]
    if language == "ar":
        head.reverse()
    data = [[_paragraph(value, styles["small"], language) for value in head]]
    for row in rows[:12]:
        values = [
            _paragraph(row.get("label") or "-", styles["small"], language),
            str(row.get("total_events", 0)),
            str(row.get("positive_count", 0)),
            str(row.get("needs_work_count", 0)),
            str(row.get("signed_points_total", 0)),
        ]
        data.append(list(reversed(values)) if language == "ar" else values)
    widths = [74 * mm, 22 * mm, 22 * mm, 24 * mm, 22 * mm]
    table = Table(data, colWidths=list(reversed(widths)) if language == "ar" else widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EDE9FE")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#312E81")),
        ("FONTNAME", (0, 0), (-1, 0), _register_fonts()[1]),
        ("FONTNAME", (0, 1), (-1, -1), _register_fonts()[0]),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return [KeepTogether([_paragraph(heading, styles["heading"], language), table]), Spacer(1, 4 * mm)]


def render_behaviour_report_pdf(bundle: dict[str, Any], language: Language = "en") -> bytes:
    copy = COPY[language]
    styles = _styles(language)
    output = io.BytesIO()
    school_name = bundle["school_name_ar"] if language == "ar" and bundle.get("school_name_ar") else bundle["school_name"]
    doc = SimpleDocTemplate(
        output,
        pagesize=A4,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
        topMargin=15 * mm,
        bottomMargin=18 * mm,
        title=copy["behaviour_report"],
        author="Class Hero Hub",
    )
    filters = bundle["filters"]
    scope = bundle.get("scope_label") or copy["school"]
    filter_labels = bundle.get("filter_labels") or []
    story = [
        _paragraph(school_name, styles["heading"], language),
        _paragraph(copy["behaviour_report"], styles["title"], language),
        _paragraph(copy["private"], styles["small"], language),
        Spacer(1, 5 * mm),
        _paragraph(f"{copy['period']}: {filters['date_from']} - {filters['date_to']}", styles["body"], language),
        _paragraph(f"{copy['scope']}: {scope}", styles["body"], language),
        _paragraph(f"{copy['filters']}: {', '.join(filter_labels) if filter_labels else copy['all']}", styles["body"], language),
        Spacer(1, 5 * mm),
    ]
    metrics = bundle["metrics"]
    metric_rows = [
        (copy["total"], metrics["total_events"]),
        (copy["positive"], metrics["positive_count"]),
        (copy["needs_work"], metrics["needs_work_count"]),
        (copy["ratio"], f"{metrics.get('positive_ratio', 0) * 100:.1f}%"),
        (copy["students"], metrics["active_students"]),
        (copy["teachers"], metrics.get("active_teachers", 0)),
        (copy["points"], metrics["signed_points_total"]),
    ]
    if language == "ar":
        metric_rows.reverse()
    metric_data = [
        [_paragraph(label, styles["small"], language) for label, _value in metric_rows],
        [_paragraph(value, styles["metric"], language) for _label, value in metric_rows],
    ]
    metric_table = Table(metric_data, colWidths=[24 * mm] * len(metric_rows), rowHeights=[9 * mm, 11 * mm])
    metric_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#E2E8F0")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.extend([metric_table, Spacer(1, 6 * mm)])

    trend = bundle.get("trends") or []
    if trend:
        trend_rows = [
            {
                "label": row["date"],
                "total_events": row["total_events"],
                "positive_count": row["positive_count"],
                "needs_work_count": row["needs_work_count"],
                "signed_points_total": row["signed_points_total"],
            }
            for row in trend[-14:]
        ]
        story.extend(_summary_table(trend_rows, copy["trend"], language, styles, label_heading=copy["date"]))
    for key, label in (("classes", copy["classes"]), ("grades", copy["grades"]), ("subjects", copy["subjects"]), ("categories", copy["categories"])):
        story.extend(_summary_table(bundle.get("breakdowns", {}).get(key, []), label, language, styles))

    events = bundle.get("events") or []
    if events:
        story.append(_paragraph(copy["event_register"], styles["heading"], language))
        headers = [copy["time"], copy["student"], copy["staff"], copy["category"], copy["points"], copy["context"]]
        if language == "ar":
            headers.reverse()
        event_data = [[_paragraph(value, styles["small"], language) for value in headers]]
        for row in events:
            context = row.get("class_section_name") or row.get("subject_name") or row.get("duty_context") or row.get("context_type") or "-"
            values = [
                _paragraph(str(row.get("created_at", ""))[:19], styles["small"], language),
                _paragraph(row.get("student_display_name") or "-", styles["small"], language),
                _paragraph(row.get("staff_display_name") or "-", styles["small"], language),
                _paragraph(row.get("category_label") or "-", styles["small"], language),
                str(row.get("points_delta", 0)),
                _paragraph(context, styles["small"], language),
            ]
            event_data.append(list(reversed(values)) if language == "ar" else values)
        event_widths = [28 * mm, 34 * mm, 31 * mm, 35 * mm, 14 * mm, 35 * mm]
        event_table = Table(event_data, colWidths=list(reversed(event_widths)) if language == "ar" else event_widths, repeatRows=1)
        event_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EDE9FE")),
            ("FONTNAME", (0, 0), (-1, 0), _register_fonts()[1]),
            ("FONTNAME", (0, 1), (-1, -1), _register_fonts()[0]),
            ("FONTSIZE", (0, 0), (-1, -1), 6.5),
            ("GRID", (0, 0), (-1, -1), 0.2, colors.HexColor("#CBD5E1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(event_table)
    story.extend([Spacer(1, 5 * mm), _paragraph(copy["generated"], styles["small"], language)])
    doc.build(
        story,
        onFirstPage=lambda canvas, document: _footer(canvas, document, language=language, school_name=school_name),
        onLaterPages=lambda canvas, document: _footer(canvas, document, language=language, school_name=school_name),
    )
    return output.getvalue()


def render_behaviour_report_csv(bundle: dict[str, Any], language: Language = "en") -> bytes:
    copy = COPY[language]
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\r\n")
    school_name = bundle["school_name_ar"] if language == "ar" and bundle.get("school_name_ar") else bundle["school_name"]
    filters = bundle["filters"]
    writer.writerow([_csv_safe(value) for value in (copy["behaviour_report"], school_name)])
    writer.writerow([_csv_safe(value) for value in (copy["period"], filters["date_from"], filters["date_to"])])
    writer.writerow([_csv_safe(value) for value in (copy["scope"], bundle.get("scope_label") or copy["school"])])
    writer.writerow([_csv_safe(value) for value in (copy["filters"], "; ".join(bundle.get("filter_labels") or []) or copy["all"])])
    writer.writerow([])
    writer.writerow([copy["time"], copy["student"], copy["staff"], copy["category"], copy["positive"], copy["points"], copy["context"]])
    for row in bundle.get("events") or []:
        context = row.get("class_section_name") or row.get("subject_name") or row.get("duty_context") or row.get("context_type") or ""
        writer.writerow([_csv_safe(value) for value in [
            row.get("created_at"),
            row.get("student_display_name"),
            row.get("staff_display_name"),
            row.get("category_label"),
            row.get("category_type") == "positive",
            row.get("points_delta"),
            context,
        ]])
    return ("\ufeff" + output.getvalue()).encode("utf-8")


def render_recognition_certificate_pdf(payload: dict[str, Any], language: Language = "en") -> bytes:
    copy = COPY[language]
    styles = _styles(language)
    output = io.BytesIO()
    school_name = payload.get("school_name_ar") if language == "ar" and payload.get("school_name_ar") else payload["school_name"]
    recipient = payload.get("student_name_ar") if language == "ar" and payload.get("student_name_ar") else payload["student_name"]
    accent, pale = ACCENTS.get(payload.get("accent_color"), ACCENTS["gold"])
    styles["certificate_name"].textColor = accent
    doc = SimpleDocTemplate(
        output,
        pagesize=landscape(A4),
        leftMargin=24 * mm,
        rightMargin=24 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        title=copy["certificate"],
        author="Class Hero Hub",
    )
    certificate = [
        Spacer(1, 8 * mm),
        _paragraph(school_name, styles["centre_bold"], language),
        Spacer(1, 8 * mm),
        _paragraph(copy["certificate"], styles["certificate_title"], language),
        Spacer(1, 10 * mm),
        _paragraph(copy["presented_to"], styles["centre"], language),
        Spacer(1, 4 * mm),
        _paragraph(recipient, styles["certificate_name"], language),
        Spacer(1, 5 * mm),
        _paragraph(payload.get("certificate_title") or copy["certificate"], styles["centre_bold"], language),
    ]
    if payload.get("citation"):
        certificate.extend([Spacer(1, 5 * mm), _paragraph(payload["citation"], styles["centre"], language)])
    certificate.extend([
        Spacer(1, 8 * mm),
        _paragraph(f"{copy['award_period']}: {payload['period_start']} - {payload['period_end']}", styles["centre"], language),
        Spacer(1, 10 * mm),
        _paragraph(payload.get("signatory_text") or "", styles["centre"], language),
        Spacer(1, 5 * mm),
        _paragraph(copy["certificate_private"], styles["small"], language),
    ])

    def border(canvas, document):
        canvas.saveState()
        canvas.setFillColor(pale)
        canvas.rect(0, 0, landscape(A4)[0], landscape(A4)[1], stroke=0, fill=1)
        canvas.setStrokeColor(accent)
        canvas.setLineWidth(4)
        canvas.rect(12 * mm, 12 * mm, landscape(A4)[0] - 24 * mm, landscape(A4)[1] - 24 * mm, stroke=1, fill=0)
        canvas.restoreState()

    doc.build(certificate, onFirstPage=border)
    return output.getvalue()
