[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=3
repo1-retention-diff=7
start-fast=y
process-max=2
log-level-console=info
lock-path=/var/lib/pgbackrest/lock
spool-path=/var/lib/pgbackrest/spool
log-path=/var/log/pgbackrest

[fhh]
pg1-path=/var/lib/postgresql/data
pg1-user=familyhero
